variable "aws_region" {
  description = "The AWS region to deploy resources in."
  type        = string
  default     = "ap-southeast-1"
}

variable "aws_profile" {
  description = "The AWS profile to use for authentication."
  type        = string
  default     = "sicepat-experiment"
}

variable "instance_type" {
  type        = string
  description = "The type of instance to launch."
  default     = "t3.nano"
}

variable "subnet_id" {
  type        = string
  description = "The ID of the Subnet to launch the instance into."

  validation {
    condition     = length(regexall("^subnet-[\\d|\\w]+$", var.subnet_id)) == 1
    error_message = "The subnet_id must match the pattern ^subnet-[\\d|\\w]+$"
  }
}
variable "name_prefix" {
  type        = string
  description = "The prefix to apply to the beginning of names generated by this module."
  default     = "Hello World"
}

variable "tags" {
  type        = map(string)
  description = "Key/Value pairs to pass to AWS as Tags."
  default     = {}
}

variable "instance_count" {
  type        = number
  description = "The number of instances to launch."
  default     = 0
  validation {
    condition     = can(parseint(tostring(var.instance_count), 10))
    error_message = "The instance count must be a whole number."
  }

  validation {
    condition     = var.instance_count >= 0
    error_message = "The instance count can not be negative."
  }
}

variable "enable_systems_manager" {
  type        = bool
  description = "When enabled the Systems Manager IAM Policy will be attached to the instance."
  default     = false
}
